name: Checking filter validity

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: lib

      - name: Checkout the adaptivefiltering repository
        uses: actions/checkout@v2
        with:
          path: af
          repository: ssciwr/adaptivefiltering

      - name: Create adaptivefiltering conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: adaptivefiltering
          environment-file: af/environment.yml
          use-only-tar-bz2: true

      - name: Install adaptivefiltering Python package
        run: |
          python -m pip install af

      - name: Check all contained filters for their validity
        shell: python
        working-directory: af
        run: |
          import adaptivefiltering
          adaptivefiltering.add_filter_library("library")
