name: PyPI deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  pypi-deploy:
    name: Deploying Python Package
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Install Python

    - name: Bump version
      uses: remorses/bump-version@js
      with:
          version_file: ./setup.cfg
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build source distribution
      run: |
        python setup.py sdist

    - uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
